const keysLayoutRu = [
  [{ key1: '>', key2: '<', code: 'Backquote' },
    { key1: '1', key2: '!', code: 'Digit1' },
    { key1: '2', key2: '"', code: 'Digit2' },
    { key1: '3', key2: '№', code: 'Digit3' },
    { key1: '4', key2: '%', code: 'Digit4' },
    { key1: '5', key2: ':', code: 'Digit5' },
    { key1: '6', key2: ',', code: 'Digit6' },
    { key1: '7', key2: '.', code: 'Digit7' },
    { key1: '8', key2: ';', code: 'Digit8' },
    { key1: '9', key2: '(', code: 'Digit9' },
    { key1: '0', key2: ')', code: 'Digit0' },
    { key1: '-', key2: '_', code: 'Minus' },
    { key1: '=', key2: '+', code: 'Equal' },
    { key1: 'Backspace', code: 'Backspace' },
  ],
  [
    { key1: 'Tab', code: 'Tab' },
    { key1: 'Й', code: 'KeyQ' },
    { key1: 'Ц', code: 'KeyW' },
    { key1: 'У', code: 'KeyE' },
    { key1: 'К', code: 'KeyR' },
    { key1: 'Е', code: 'KeyT' },
    { key1: 'Н', code: 'KeyY' },
    { key1: 'Г', code: 'KeyU' },
    { key1: 'Ш', code: 'KeyI' },
    { key1: 'Щ', code: 'KeyO' },
    { key1: 'З', code: 'KeyP' },
    { key1: 'Х', code: 'BracketLeft' },
    { key1: 'Ъ', code: 'BracketRight' },
    { key1: 'Enter', code: 'Enter' },

  ],
  [
    { key1: 'Caps Lock', code: 'CapsLock' },
    { key1: 'Ф', code: 'KeyA' },
    { key1: 'Ы', code: 'KeyS' },
    { key1: 'В', code: 'KeyD' },
    { key1: 'А', code: 'KeyF' },
    { key1: 'П', code: 'KeyG' },
    { key1: 'Р', code: 'KeyH' },
    { key1: 'О', code: 'KeyJ' },
    { key1: 'Л', code: 'KeyK' },
    { key1: 'Д', code: 'KeyL' },
    { key1: 'Ж', code: 'Semicolon' },
    { key1: 'Э', code: 'Quote' },
    { key1: 'Ё', code: 'Backslash' },
  ],
  [
    { key1: 'Shift', code: 'ShiftLeft' },
    { key1: ']', key2: '[', code: 'IntlBackslash' },
    { key1: 'Я', code: 'KeyZ' },
    { key1: 'Ч', code: 'KeyX' },
    { key1: 'С', code: 'KeyC' },
    { key1: 'М', code: 'KeyV' },
    { key1: 'И', code: 'KeyB' },
    { key1: 'Т', code: 'KeyN' },
    { key1: 'Ь', code: 'KeyM' },
    { key1: 'Б', code: 'Comma' },
    { key1: 'Ю', code: 'Period' },
    { key1: '/', key2: '?', code: 'Slash' },
    { key1: 'Shift', code: 'ShiftRight' },
  ],
  [
    { key1: 'fn', code: 'Fn' },
    { key1: 'Control', code: 'ControlLeft' },
    { key1: 'Option', code: 'AltLeft' },
    { key1: 'Command', code: 'MetaLeft' },
    { key1: 'Space', code: 'Space' },
    { key1: 'Command', code: 'MetaRight' },
    { key1: 'Option', code: 'AltRight' },
    { key1: '&#8249;', code: 'ArrowLeft' },
    [{ key1: '\t&#8743;', code: 'ArrowUp' }, { key1: '\t&#8744;', code: 'ArrowDown' }],
    { key1: '\t&#8250;', code: 'ArrowRight' },
  ],
];

export default keysLayoutRu;
