const keysLayoutEn = [
  [{ key1: '§', key2: '±', code: 'Backquote' },
    { key1: '1', key2: '!', code: 'Digit1' },
    { key1: '2', key2: '@', code: 'Digit2' },
    { key1: '3', key2: '#', code: 'Digit3' },
    { key1: '4', key2: '$', code: 'Digit4' },
    { key1: '5', key2: '%', code: 'Digit5' },
    { key1: '6', key2: '^', code: 'Digit6' },
    { key1: '7', key2: '&', code: 'Digit7' },
    { key1: '8', key2: '*', code: 'Digit8' },
    { key1: '9', key2: '(', code: 'Digit9' },
    { key1: '0', key2: ')', code: 'Digit0' },
    { key1: '-', key2: '_', code: 'Minus' },
    { key1: '=', key2: '+', code: 'Equal' },
    { key1: 'Backspace', code: 'Backspace' },
  ],
  [
    { key1: 'Tab', code: 'Tab' },
    { key1: 'Q', code: 'KeyQ' },
    { key1: 'W', code: 'KeyW' },
    { key1: 'E', code: 'KeyE' },
    { key1: 'R', code: 'KeyR' },
    { key1: 'T', code: 'KeyT' },
    { key1: 'Y', code: 'KeyY' },
    { key1: 'U', code: 'KeyU' },
    { key1: 'I', code: 'KeyI' },
    { key1: 'O', code: 'KeyO' },
    { key1: 'P', code: 'KeyP' },
    { key1: '[', key2: '{', code: 'BracketLeft' },
    { key1: ']', key2: '}', code: 'BracketRight' },
    { key1: 'Enter', code: 'Enter' },

  ],
  [
    { key1: 'Caps Lock', code: 'CapsLock' },
    { key1: 'A', code: 'KeyA' },
    { key1: 'S', code: 'KeyS' },
    { key1: 'D', code: 'KeyD' },
    { key1: 'F', code: 'KeyF' },
    { key1: 'G', code: 'KeyG' },
    { key1: 'H', code: 'KeyH' },
    { key1: 'J', code: 'KeyJ' },
    { key1: 'K', code: 'KeyK' },
    { key1: 'L', code: 'KeyL' },
    { key1: ';', key2: ':', code: 'Semicolon' },
    { key1: '\'', key2: '"', code: 'Quote' },
    { key1: '\\', key2: '|', code: 'Backslash' },
  ],
  [
    { key1: 'Shift', code: 'ShiftLeft' },
    { key1: '`', key2: '~', code: 'IntlBackslash' },
    { key1: 'Z', code: 'KeyZ' },
    { key1: 'X', code: 'KeyX' },
    { key1: 'C', code: 'KeyC' },
    { key1: 'V', code: 'KeyV' },
    { key1: 'B', code: 'KeyB' },
    { key1: 'N', code: 'KeyN' },
    { key1: 'M', code: 'KeyM' },
    { key1: ',', key2: '<', code: 'Comma' },
    { key1: '.', key2: '>', code: 'Period' },
    { key1: '/', key2: '?', code: 'Slash' },
    { key1: 'Shift', code: 'ShiftRight' },
  ],
  [
    { key1: 'fn', code: 'Fn' },
    { key1: 'Control', code: 'ControlLeft' },
    { key1: 'Option', code: 'AltLeft' },
    { key1: 'Command', code: 'MetaLeft' },
    { key1: 'Space', code: 'Space' },
    { key1: 'Command', code: 'MetaRight' },
    { key1: 'Option', code: 'AltRight' },
    { key1: '&#8249;', code: 'ArrowLeft' },
    [{ key1: '\t&#8743;', code: 'ArrowUp' }, { key1: '\t&#8744;', code: 'ArrowDown' }],
    { key1: '\t&#8250;', code: 'ArrowRight' },
  ],
];

export default keysLayoutEn;
